polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    #/polls/
    path('', views.vistaIndex.as_view(), name='index'),
    # /polls/5/
    path('<int:pk>/', views.vistaDetalle.as_view(), name='detalle'),
    # /polls/5/resultados/
    path('<int:pk>/resultados/', views.vistaResultados.as_view() , name='resultados'),
    # /polls/5/votacion/
    path('<int:pregunta_id>/votacion/', views.votacion, name='votacion'),
]

pollsite/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone


# Create your models here.
class Pregunta(models.Model):
    enunciado_pregunta = models.CharField(max_length=200)

    fecha_pub = models.DateTimeField('fecha de publicación')

    def __str__(self):
        #return str(self.id) + " - " + str(self.enunciado_pregunta)
        return str(self.enunciado_pregunta)

    def fue_publicada_recientemente(self):
        ahora = timezone.now()
        return ahora - datetime.timedelta(days=1) <= self.fecha_pub <= ahora

class Opcion(models.Model):
    pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE)

    texto_opcion = models.CharField(max_length=200)

    votos = models.IntegerField(default=0)

    def __str__(self):
        return self.texto_opcion

polls/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, render

#Borrar httpresponse y loader cuando se cambien todos los métodos para que usen render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader

from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Pregunta, Opcion


class vistaIndex(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'lista_preguntas_actualizada'

    def get_queryset(self):
        #incluye las últimas 5 preguntas sin incluir las futuras
        return Pregunta.objects.filter(
            fecha_pub__lte=timezone.now()
        ).order_by('-fecha_pub')[:5]

class vistaDetalle(generic.DetailView):
    model = Pregunta
    template_name = 'polls/detalle.html'
    def get_queryset(self):
        #excluye preguntas que no han sido publicadas
        return Pregunta.objects.filter(fecha_pub__lte=timezone.now())

class vistaResultados(generic.DetailView):
    model = Pregunta
    template_name = 'polls/resultados.html'

def votacion(request, pregunta_id):

    pregunta = get_object_or_404(Pregunta, pk=pregunta_id)

    try:
        opcion_seleccionada = pregunta.opcion_set.get(pk=request.POST['opcion'])
    except (KeyError, Pregunta.DoesNotExist):

        #vuelve a cargar la pregunta si hay un error asignando la opción
        return render(request, 'polls/detalle.html', {
            'pregunta': pregunta,
            'mensaje_error': "No se ha seleccionado ninguna opción",
        })
    else:
        opcion_seleccionada.votos +=1
        opcion_seleccionada.save()
        return HttpResponseRedirect(reverse('polls:resultados', args=(pregunta.id,)))

polls/templates/polls/detalle.html
<h1>{{ pregunta.enunciado_pregunta }}</h1>

{% if mensaje_error %}<p><strong>{{ mensaje_error }}</strong></p>{% endif %}

<form action="{% url 'polls:votacion' pregunta.id %}" method="post">
	{% csrf_token %}
	{% for opcion in pregunta.opcion_set.all %}
		<input type="radio" name="opcion" id="opcion{{ forloop.counter }}" value="{{ opcion.id }}">
		<label for="opcion{{ forloop.counter }}">{{ opcion.texto_opcion }}</label>
		<br>
	{% endfor %}
	<input type="submit" value="Votar">
</form>

polls/templates/polls/index.html
{% if lista_preguntas_actualizada %}
    <ul>
    {% for pregunta in lista_preguntas_actualizada %}
        <li><a href="{% url 'polls:detalle' pregunta.id %}">{{ pregunta.enunciado_pregunta }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No hay preguntas disponibles.</p>
{% endif %}

polls/templates/polls/resultados.html
<h1>{{ pregunta.enunciado_pregunta }}</h1>

<ul>
	{% for opcion in pregunta.opcion_set.all %}
		<li>{{ opcion.texto_opcion }} -- {{ opcion.votos }} voto{{ opcion.votos|pluralize }}</li>
	{% endfor %}
</ul>

<a href="{% url 'polls:detalle' pregunta.id %}">¿Votar de nuevo?</a>